{% set data= load_setup_py_data() %}
package:
  name: ts-standardscripts
  version: {{ data.get('version') }}

source:
  path: ../

build:
  script: python -m pip install --no-deps --ignore-installed .
  script_env:
    - PATH
    - PYTHONPATH
    - LD_LIBRARY_PATH
    - OSPL_HOME
    - OSPL_URI
    - PYTHON_BUILD_VERSION
    - PYTHON_BUILD_LOCATION
    - LSST_DDS_DOMAIN_ID
    - LSST_DDS_HISTORYSYNC
    - OSPL_MASTER_PRIORITY
    - TS_CONFIG_OCS_DIR
    - TS_CONFIG_ATTCS_DIR

test:
  requires:
    - astroquery
    - ts-atdome
    - ts-atdometrajectory
    - ts-atmcs-simulator
    - ts-conda-build
    - ts-idl
    - ts-observatory-control
    - ts-salobj
  source_files:
    - python
    - tests
    - scripts
    - setup.cfg
  commands:
    - py.test -vxs

requirements:
  host:
    - python
    - pip
    - setuptools_scm
    - setuptools
    - pytest-runner
  run:
    - python
    - setuptools
    - setuptools_scm
    - ts-idl
    - ts-salobj
    - ts-observatory-control
